name: 🚀 AWS DevOps Deployment
 
on:
  workflow_dispatch:
    inputs:
      cleanup:
        description: "Auto delete instances after demo?"
        required: true
        default: "yes"
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
 
    - name: 📥 Checkout Code
      uses: actions/checkout@v3
 
    - name: 🔧 Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
 
    - name: ⚙️ Make Scripts Executable
      run: |
        chmod +x deploy.sh
        chmod +x linux_instances.sh
        chmod +x window_instances.sh
 
    - name: 🚀 Run Deployment
      run: |
        echo "🚀 Starting Deployment..."
        ./deploy.sh
 
    - name: ⏳ Wait for Demo (5 minutes)
      run: |
        echo "⏳ You have 5 minutes to test your applications..."
        sleep 300
 
    - name: ⚠️ Manual Cleanup Reminder
      if: ${{ github.event.inputs.cleanup == 'no' }}
      run: |
        echo "⚠️ Auto cleanup is disabled!"
        echo "👉 Please terminate instances manually from AWS console to avoid charges."
 
    - name: 💣 Auto Cleanup
      if: ${{ github.event.inputs.cleanup == 'yes' }}
      run: |
        echo "🧹 Cleaning up all running EC2 instances..."
 
        IDS=$(aws ec2 describe-instances \
        --filters "Name=instance-state-name,Values=running" \
        --query "Reservations[*].Instances[*].InstanceId" \
        --output text)
 
        if [ -n "$IDS" ]; then
          aws ec2 terminate-instances --instance-ids $IDS
          echo "✅ Instances terminated successfully"
        else
          echo "ℹ️ No running instances found"
        fi
 
